export { default as Homepage } from './homepage.jsx';
export { default as EventDetails } from './eventDetails.jsx';
export { default as Auth } from './auth.jsx';
export { default as RegistrationsForms } from './registrations';
export { default as Payment } from './payment.jsx';
export { default as Dashboard } from './dashboard.jsx';
export { default as InCTeams } from './incTeams.jsx';
export { default as WebTeam } from './webTeam.jsx';
export { default as FacultyTeam } from './facultyTeam.jsx';
// export {default as Gallery} from './gallery.jsx';
export { default as Admin } from './admin';
export { default as ProjectsLabsAllocations } from './allocations.labs.jsx';