export {
    loginAdmin,
    registerJudge,
    registerEventStep1,
    registerEventStep2,
    registerEventStep3,
    registerEventStep4,
    verifyPayment,
    verifyAdmin,
    getPendingPayments,
    getRegistrations,
    viewJudges,
    allocateJudge,
    getJudgeAllocations,
    deallocateJudge,
    evaluateProject,
    getJudge,
    getLabAllocations,
} from './requests';